# Generated by Django 5.1.2 on 2024-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_items_price_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dp',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
