# Generated by Django 5.1.2 on 2024-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
