# Generated by Django 5.1.2 on 2024-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_paymethods_orders_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymethods',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
