# Generated by Django 5.1.2 on 2024-11-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_items_orders_item_alter_orders_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='dp',
            new_name='discription',
        ),
    ]
