# Generated by Django 5.1.2 on 2024-11-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_orders_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='name',
            new_name='user',
        ),
    ]
