# Generated by Django 5.1.2 on 2024-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_name_owners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='user',
        ),
        migrations.AddField(
            model_name='owners',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
