# Generated by Django 5.1.2 on 2024-11-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_owners_user_owners_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='name',
            new_name='owner_name',
        ),
    ]
